name: Chrome
flatpak: com.google.Chrome
system_bin: google-chrome-stable
can_isolate: true
can_start_maximized: true
desktop_file_name_prefix: com.google.Chrome.chrome
base: chromium
issues:
  en:
    - Does not remember window size and position
  nl:
    - Onthoudt de grootte en positie van het venster niet
  es:
    - No recuerda el tamaño ni posición de la ventana
  it:
    - Non ricorda le dimensioni e la posizione della finestra
