name: Firefox
flatpak: org.mozilla.firefox
system_bin: firefox
can_isolate: true
desktop_file_name_prefix: org.mozilla.firefox.firefox
base: firefox
issues:
  en:
    - Unable to remove ui when not isolated
  nl:
    - UI kan niet worden verwijderd zonder isolatie
  it:
    - Impossibile rimuovere l'interfaccia utente se non isolata
