name: Floorp
flatpak: one.ablaze.floorp
system_bin: floorp
can_isolate: true
desktop_file_name_prefix: one.ablaze.floorp.floorp
base: firefox
issues:
  en:
    - Unable to remove ui when not isolated
  nl:
    - UI kan niet worden verwijderd zonder isolatie
  it:
    - Impossibile rimuovere l'interfaccia utente se non isolata
